#This file is for other projects to use, so that they can locate SIMULANT
#using cmake

FIND_PATH( SIMULANT_INCLUDE_DIR NAMES kglt/kglt.h PATHS /usr/include /usr/local/include $ENV{INCLUDE} )
FIND_LIBRARY( SIMULANT_LIBRARY NAMES kglt PATHS /usr/lib /usr/local/lib )

IF(SIMULANT_INCLUDE_DIR)
	MESSAGE(STATUS "Found SIMULANT include dir: ${SIMULANT_INCLUDE_DIR}")
	SET(SIMULANT_INCLUDE_DIRS 
		${SIMULANT_INCLUDE_DIR} 
		${SIMULANT_INCLUDE_DIR}/kglt/deps
		${SIMULANT_INCLUDE_DIR}/kglt/deps/kazsignal
	)
ELSE(SIMULANT_INCLUDE_DIR)
	MESSAGE(STATUS "Could NOT find SIMULANT headers.")
ENDIF(SIMULANT_INCLUDE_DIR)

IF(SIMULANT_LIBRARY)
	MESSAGE(STATUS "Found SIMULANT library: ${SIMULANT_LIBRARY}")
ELSE(SIMULANT_LIBRARY)
	MESSAGE(STATUS "Could NOT find SIMULANT library.")
ENDIF(SIMULANT_LIBRARY)

IF(SIMULANT_INCLUDE_DIR AND SIMULANT_LIBRARY)
	SET(SIMULANT_FOUND "YES")
	SET(SIMULANT_LIBRARIES ${SIMULANT_LIBRARY})
ELSE(SIMULANT_INCLUDE_DIR AND SIMULANT_LIBRARY)
	SET(SIMULANT_FOUND "NO")
	IF(SIMULANT_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find SIMULANT. Please install SIMULANT (http://github.com/kazade/kglt)")
	ENDIF(SIMULANT_FIND_REQUIRED)
ENDIF(SIMULANT_INCLUDE_DIR AND SIMULANT_LIBRARY)
