SET(CMAKE_SYSTEM_NAME Generic)
SET(PLATFORM_DREAMCAST TRUE)
set(CMAKE_CROSSCOMPILING TRUE)

INCLUDE($ENV{KOS_BASE}/utils/cmake/kallistios.toolchain.cmake)

ADD_DEFINITIONS(
  -D__DREAMCAST__
)

SET(CMAKE_EXECUTABLE_SUFFIX ".elf")
SET(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf")
