SET(CMAKE_SYSTEM_NAME KOS)

SET(CMAKE_C_COMPILER $ENV{KOS_BASE}/utils/gnu_wrappers/kos-cc)
SET(CMAKE_CXX_COMPILER $ENV{KOS_BASE}/utils/gnu_wrappers/kos-c++)
SET(CMAKE_FIND_ROOT_PATH $ENV{KOS_BASE})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
