"""Renders a TranslationUnit (see ir.py) to the .h/.c(pp) files that make up
ports/c/generated/. Headers are plain C (safe to include from C or C++);
implementation files are C++ (they call into Simulant's C++ classes) but
every wrapped symbol is exported with `extern "C"` linkage, so the resulting
object files / static library expose a pure C ABI.
"""
import os

from . import log

HEADER_BANNER = """/* Generated by tools/cgen/cgen.py -- do not edit by hand.
 * Regenerate with: python3 tools/cgen/cgen.py
 */
"""

C_LINKAGE_OPEN = """#ifdef __cplusplus
extern "C" {
#endif
"""
C_LINKAGE_CLOSE = """#ifdef __cplusplus
}
#endif
"""


def _rel_include(source_file, repo_root):
    rel = os.path.relpath(source_file, repo_root)
    return rel.replace(os.sep, "/")


def _param_decl_list(params):
    if not params:
        return "void"
    return ", ".join(f"{p.c_type} {p.name}" for p in params)


def _doc_comment(text):
    if not text:
        return ""
    return f"/* {text} */\n"


class Emitter:
    def __init__(self, out_dir, repo_root):
        self.out_dir = out_dir
        self.repo_root = repo_root
        self.include_dir = os.path.join(out_dir, "include", "simulant", "c")
        self.src_dir = os.path.join(out_dir, "src")

    def write_all(self, tu):
        os.makedirs(self.include_dir, exist_ok=True)
        os.makedirs(self.src_dir, exist_ok=True)

        self._write_types_header(tu)

        header_names = ["types"]
        for cls in tu.classes:
            self._write_class_header(cls)
            self._write_class_source(cls)
            header_names.append(cls.base_name)

        if tu.functions:
            self._write_functions_header(tu.functions)
            self._write_functions_source(tu.functions)
            header_names.append("functions")

        self._write_umbrella_header(header_names)

        n_classes = len(tu.classes)
        n_methods = sum(len(c.methods) for c in tu.classes)
        n_enums = len(tu.enums)
        n_funcs = len(tu.functions)
        n_opaque = len(tu.opaque_types) + len(tu.opaque_enum_types)
        log.status(f"generated {n_classes} classes ({n_methods} functions), {n_enums} enums, "
                   f"{n_funcs} free functions, {n_opaque} opaque-only types -> {self.out_dir}")

    # ------------------------------------------------------------------ types.h
    def _write_types_header(self, tu):
        path = os.path.join(self.include_dir, "types.h")
        lines = [HEADER_BANNER, "#pragma once", "", "#include <stdbool.h>",
                 "#include <stddef.h>", "#include <stdint.h>", "", C_LINKAGE_OPEN]

        lines.append("/* Opaque handles for wrapped classes/structs. */")
        for cls in sorted(tu.classes, key=lambda c: c.c_type):
            lines.append(f"typedef struct {cls.c_type[:-2]}_s {cls.c_type};")
        if tu.opaque_types:
            lines.append("")
            lines.append("/* Referenced but not fully wrapped (forward-declared only, or")
            lines.append(" * outside the current scan input). Only usable as an opaque pointer. */")
            for op in sorted(tu.opaque_types, key=lambda o: o.c_type):
                lines.append(f"typedef struct {op.c_type[:-2]}_s {op.c_type}; /* {op.cpp_qualified_name} */")

        if tu.enums:
            lines.append("")
            lines.append("/* Enums */")
            for enum in sorted(tu.enums, key=lambda e: e.c_type):
                lines.append(f"/* {enum.cpp_qualified_name} */")
                lines.append(f"typedef enum {enum.c_type[:-2]}_e {{")
                for value in enum.enumerators:
                    lines.append(f"    {value.c_name} = {value.value},")
                lines.append(f"}} {enum.c_type};")
                lines.append("")

        if tu.opaque_enum_types:
            lines.append("/* Enums outside the wrapped API: kept as plain int for ABI purposes. */")
            for op in sorted(tu.opaque_enum_types, key=lambda o: o.c_type):
                lines.append(f"typedef int {op.c_type}; /* {op.cpp_qualified_name} */")

        lines.append("")
        lines.append("/* Releases a string returned by any smlt_*() function. */")
        lines.append("void smlt_c_free_string(char* str);")
        lines.append("")
        lines.append(C_LINKAGE_CLOSE)

        self._write_file(path, "\n".join(lines))

    # ------------------------------------------------------------------ class header/source
    def _write_class_header(self, cls):
        path = os.path.join(self.include_dir, f"{cls.base_name}.h")
        lines = [HEADER_BANNER, "#pragma once", "", '#include "simulant/c/types.h"', "",
                 f"/* {cls.cpp_qualified_name} */", C_LINKAGE_OPEN]
        for m in cls.methods:
            lines.append(_doc_comment(m.brief) + f"{m.return_spec.c_type} {m.c_name}({_param_decl_list(m.params)});")
        if cls.is_abstract:
            lines.append("")
            lines.append("/* This class is abstract in C++ (has pure virtual methods): no")
            lines.append(" * smlt_..._create() is generated for it. Instances reached via")
            lines.append(" * other API calls can still be used with the functions above. */")
        lines.append("")
        lines.append(C_LINKAGE_CLOSE)
        self._write_file(path, "\n".join(lines))

    def _write_class_source(self, cls):
        path = os.path.join(self.src_dir, f"{cls.base_name}.cpp")
        includes = [cls.source_file] + list(cls.extra_includes)
        include_lines = [f'#include "{_rel_include(inc, self.repo_root)}"' for inc in includes]
        # <cstdint>/<cstddef> unconditionally: a header may only compile in
        # the real engine because something included earlier already
        # pulled these in (e.g. throttle.h uses uint16_t but doesn't
        # include <cstdint> itself), which we can't rely on here.
        lines = [HEADER_BANNER, "#include <cstddef>", "#include <cstdint>", "#include <memory>"] + include_lines + [
                 '#include "simulant/c/simulant_c.h"', '#include "smlt_c_util.h"', "",
                 'extern "C" {', ""]
        for m in cls.methods:
            body = m.return_spec.stmt_template.format(call=m.call_expr)
            lines.append(f"{m.return_spec.c_type} {m.c_name}({_param_decl_list(m.params)}) {{")
            lines.append(f"    {body}")
            lines.append("}")
            lines.append("")
        lines.append("} /* extern \"C\" */")
        self._write_file(path, "\n".join(lines))

    # ------------------------------------------------------------------ free functions
    def _write_functions_header(self, functions):
        path = os.path.join(self.include_dir, "functions.h")
        lines = [HEADER_BANNER, "#pragma once", "", '#include "simulant/c/types.h"', "",
                 C_LINKAGE_OPEN]
        for f in functions:
            lines.append(f"{f.return_spec.c_type} {f.c_name}({_param_decl_list(f.params)});")
        lines.append("")
        lines.append(C_LINKAGE_CLOSE)
        self._write_file(path, "\n".join(lines))

    def _write_functions_source(self, functions):
        path = os.path.join(self.src_dir, "functions.cpp")
        all_files = set()
        for f in functions:
            all_files.add(f.source_file)
            all_files.update(f.extra_includes)
        includes = sorted({_rel_include(inc, self.repo_root) for inc in all_files})
        lines = [HEADER_BANNER, "#include <cstddef>", "#include <cstdint>", "#include <memory>"]
        for inc in includes:
            lines.append(f'#include "{inc}"')
        lines.append('#include "simulant/c/simulant_c.h"')
        lines.append('#include "smlt_c_util.h"')
        lines.append("")
        lines.append('extern "C" {')
        lines.append("")
        for f in functions:
            body = f.return_spec.stmt_template.format(call=f.call_expr)
            lines.append(f"{f.return_spec.c_type} {f.c_name}({_param_decl_list(f.params)}) {{")
            lines.append(f"    {body}")
            lines.append("}")
            lines.append("")
        lines.append('} /* extern "C" */')
        self._write_file(path, "\n".join(lines))

    # ------------------------------------------------------------------ umbrella
    def _write_umbrella_header(self, header_names):
        path = os.path.join(self.include_dir, "simulant_c.h")
        lines = [HEADER_BANNER, "#pragma once", ""]
        for name in header_names:
            lines.append(f'#include "simulant/c/{name}.h"')
        lines.append("")
        self._write_file(path, "\n".join(lines))

    def _write_file(self, path, content):
        if not content.endswith("\n"):
            content += "\n"
        # Skip the write if nothing changed, so incremental (ninja/make)
        # builds don't get spurious re-compiles of downstream sources.
        if os.path.exists(path):
            with open(path, "r") as f:
                if f.read() == content:
                    log.debug(f"unchanged: {path}")
                    return
        with open(path, "w") as f:
            f.write(content)
        log.info(f"wrote {path}")
