#pragma once

namespace smlt {

enum BuiltInStageNodeType {
    STAGE_NODE_TYPE_STAGE,
    STAGE_NODE_TYPE_CAMERA,
    STAGE_NODE_TYPE_ACTOR,
    STAGE_NODE_TYPE_LIGHT,
    STAGE_NODE_TYPE_PARTICLE_SYSTEM,
    STAGE_NODE_TYPE_GEOM,
    STAGE_NODE_TYPE_MESH_INSTANCER,
    STAGE_NODE_TYPE_SKYBOX,
    STAGE_NODE_TYPE_SPRITE,
    STAGE_NODE_TYPE_WIDGET,
    STAGE_NODE_TYPE_DEBUG,
    STAGE_NODE_TYPE_USER_BASE = 1000
};

typedef uint32_t StageNodeType;

}
